# Generated by Django 6.0.5 on 2026-06-04 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('group', models.CharField(blank=True, max_length=1, null=True)),
                ('flag', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'National Team',
                'verbose_name_plural': 'National Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SweepstakeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'verbose_name': 'Sweepstake Team',
                'verbose_name_plural': 'Sweepstake Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('group_stage', 'Group Stage'), ('round_of_32', 'Round of 32'), ('round_of_16', 'Round of 16'), ('quarterfinals', 'Quarter-finals'), ('semifinals', 'Semi-finals'), ('third_place', 'Third Place'), ('final', 'Final')], max_length=20)),
                ('kickoff', models.DateTimeField()),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('knockout_winner', models.CharField(blank=True, help_text='Knockout only: who advanced (home/away) after extra time/pens', max_length=4, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='bets.nationalteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='bets.nationalteam')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['kickoff'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_from_team_stats', models.BooleanField(default=False, help_text="Exclude this user's points from their team's leaderboard stats.")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='bets.sweepstaketeam')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_winner', models.CharField(choices=[('home', 'Home Win'), ('away', 'Away Win'), ('draw', 'Draw')], max_length=10)),
                ('predicted_home_goals', models.IntegerField(blank=True, null=True)),
                ('predicted_away_goals', models.IntegerField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='bets.match')),
            ],
            options={
                'verbose_name': 'Bet',
                'verbose_name_plural': 'Bets',
                'unique_together': {('user', 'match')},
            },
        ),
    ]
