# Generated by Django 4.2.30 on 2026-06-14 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0003_unique_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweepstake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('invite_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sweepstake',
                'verbose_name_plural': 'Sweepstakes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='excluded_from_team_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_members', to='bets.sweepstaketeam'),
        ),
        migrations.AddField(
            model_name='sweepstaketeam',
            name='sweepstake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='bets.sweepstake'),
        ),
        migrations.CreateModel(
            name='SweepstakeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_from_team_stats', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('sweepstake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='bets.sweepstake')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='bets.sweepstaketeam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sweepstake Membership',
                'verbose_name_plural': 'Sweepstake Memberships',
                'ordering': ['sweepstake__name', 'user__username'],
                'unique_together': {('user', 'sweepstake')},
            },
        ),
    ]
